### ISSUE TITLE
Nice resource!!

### ISSUE THREAD

**Issue by torarnv** [GreenYun/Zhengma-macOS#1]
Where did you find info on the various input method Plist keys?

Is there a way to extract the contents of `AppleKeyboardLayouts-L.dat`?

Thanks!

**Comment by GreenYun** [comment]
I have extracted some Plist files and looked for keys that may be useful to me. And I tried all the keys and their possible values to see effects.

This repo will be updated once I have made the input method for Zhengma on macOS. There are still lots of problems to resolve and I will put more notes to the wiki pages.

You mentioned `AppleKeyboardLayouts-L.dat` which I never know anything about before, and I spent my holiday decoding that. Take a look at this [repo](https://github.com/GreenYun/layout-dat), and I would be pleased if you create issues for questions or suggestions about that.

I will close this issue. If you have more questions, feel free to ask again.
